import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export default {
  configureHooks(config, installDir) {
    // Codex CLI uses AGENTS.md for instructions
    const agentsPath = join(config.configDir, "AGENTS.md");

    // Create reference to ArkaOS instructions
    const arkaosRef = `# ArkaOS v2 Configuration

> Auto-generated by ArkaOS installer. Do not edit manually.

## System Instructions

ArkaOS is installed at: ${installDir}
Load instructions from: ${join(installDir, "config", "codex-instructions.md")}

## Available Commands

Use natural language or prefix commands:
- /do <description> — Universal orchestrator
- /dev, /mkt, /fin, /strat, /brand, /ops, /ecom, /kb, /saas, /landing, /community, /content

## Hooks

Codex CLI does not support native hooks. Context is injected via instruction files.
`;

    mkdirSync(config.configDir, { recursive: true });
    writeFileSync(agentsPath, arkaosRef);
    console.log("         Codex CLI AGENTS.md configured.");
  },
};
