import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export default {
  configureHooks(config, installDir) {
    // Gemini CLI uses GEMINI.md for instructions
    const geminiMdPath = join(config.configDir, "GEMINI.md");

    const arkaosRef = `# ArkaOS v2 Configuration

> Auto-generated by ArkaOS installer. Do not edit manually.

## System Instructions

ArkaOS is installed at: ${installDir}
Load instructions from: ${join(installDir, "config", "gemini-instructions.md")}

## Available Commands

Use natural language or prefix commands:
- /do <description> — Universal orchestrator
- /dev, /mkt, /fin, /strat, /brand, /ops, /ecom, /kb, /saas, /landing, /community, /content

## Tool Mapping

Gemini CLI tools map to ArkaOS tools:
- activate_skill → Skill invocation
- read_file → Read
- edit_file → Edit
- run_command → Bash
`;

    mkdirSync(config.configDir, { recursive: true });
    writeFileSync(geminiMdPath, arkaosRef);
    console.log("         Gemini CLI GEMINI.md configured.");
  },
};
