"""Pydantic schemas for the ArkaOS Cognitive Layer memory system.

Three core models:
- RawCapture: Raw session captures during the day
- KnowledgeEntry: Curated knowledge for dual-write (SQLite + Obsidian)
- ActionableInsight: Insights for proactive presentation to the user
"""

import uuid
from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field, field_validator


# --- Allowed categories and statuses ---

RAW_CAPTURE_CATEGORIES = ("decision", "solution", "pattern", "error", "config")

KNOWLEDGE_ENTRY_CATEGORIES = (
    "pattern",
    "anti_pattern",
    "solution",
    "architecture",
    "config",
    "lesson",
    "improvement",
)

ACTIONABLE_INSIGHT_CATEGORIES = ("business", "technical", "ux", "strategy")

ACTIONABLE_INSIGHT_SEVERITIES = ("rethink", "improve", "consider")

ACTIONABLE_INSIGHT_STATUSES = ("pending", "presented", "accepted", "dismissed")


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


# --- Models ---

class RawCapture(BaseModel):
    """Raw session capture — recorded during active work sessions."""

    id: str = Field(default_factory=_new_uuid)
    timestamp: datetime = Field(default_factory=_utc_now)
    session_id: str
    project_path: str
    project_name: str
    category: str
    content: str
    context: dict = Field(default_factory=dict)

    @field_validator("category")
    @classmethod
    def validate_category(cls, v: str) -> str:
        if v not in RAW_CAPTURE_CATEGORIES:
            raise ValueError(
                f"Invalid category '{v}'. Must be one of: {RAW_CAPTURE_CATEGORIES}"
            )
        return v


class KnowledgeEntry(BaseModel):
    """Curated knowledge entry — written to SQLite and Obsidian on dual-write."""

    id: str = Field(default_factory=_new_uuid)
    title: str
    category: str
    tags: list[str] = Field(default_factory=list)
    stacks: list[str] = Field(default_factory=list)
    content: str
    source_project: str
    applicable_to: str = "any"
    confidence: float = 0.5
    times_used: int = 0
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)

    @field_validator("category")
    @classmethod
    def validate_category(cls, v: str) -> str:
        if v not in KNOWLEDGE_ENTRY_CATEGORIES:
            raise ValueError(
                f"Invalid category '{v}'. Must be one of: {KNOWLEDGE_ENTRY_CATEGORIES}"
            )
        return v

    @field_validator("confidence")
    @classmethod
    def clamp_confidence(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class ActionableInsight(BaseModel):
    """Actionable insight — generated by agents for proactive presentation."""

    id: str = Field(default_factory=_new_uuid)
    project: str
    trigger: str
    date_generated: datetime = Field(default_factory=_utc_now)
    category: str
    severity: str
    title: str
    description: str
    recommendation: str
    context: str
    status: str = "pending"
    presented_at: datetime | None = None

    @field_validator("category")
    @classmethod
    def validate_category(cls, v: str) -> str:
        if v not in ACTIONABLE_INSIGHT_CATEGORIES:
            raise ValueError(
                f"Invalid category '{v}'. Must be one of: {ACTIONABLE_INSIGHT_CATEGORIES}"
            )
        return v

    @field_validator("severity")
    @classmethod
    def validate_severity(cls, v: str) -> str:
        if v not in ACTIONABLE_INSIGHT_SEVERITIES:
            raise ValueError(
                f"Invalid severity '{v}'. Must be one of: {ACTIONABLE_INSIGHT_SEVERITIES}"
            )
        return v

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        if v not in ACTIONABLE_INSIGHT_STATUSES:
            raise ValueError(
                f"Invalid status '{v}'. Must be one of: {ACTIONABLE_INSIGHT_STATUSES}"
            )
        return v
